INSERT INTO activities (name, description) VALUES ("Pottery", "Making pottery");
INSERT INTO activities (name, description) VALUES ("3D Printing", "Print a 3D object of choice");
INSERT INTO activities (name, description) VALUES ("Swimming", "Swim at nearby lakes and waterparks");
INSERT INTO activities (name, description) VALUES ("Hiking", "Hike nearby peaks");
INSERT INTO activities (name, description) VALUES ("Soccer", "Play soccer");
INSERT INTO activities (name, description) VALUES ("Programming", "Learn basic coding languages");
INSERT INTO activities (name, description) VALUES ("Robotics", "Learn how to build a robot from scratch");
INSERT INTO activities (name, description) VALUES ("Tennis", "Tennis lessons available for all levels");
INSERT INTO activities (name, description) VALUES ("Kayaking", "Kayak and race against your friends");
INSERT INTO activities (name, description) VALUES ("Basketball", "Join a team for our basketball tournament");
INSERT INTO activities (name, description) VALUES ("Pre-programming", "Learn math programming foundations");
INSERT INTO activities (name, description) VALUES ("Rock climbing", "Join us as attend a rock climbing gym");
INSERT INTO activities (name, description) VALUES ("Baseball", "Baseball and softball tournaments");
INSERT INTO activities (name, description) VALUES ("Biking", "Mountain biking");
INSERT INTO activities (name, description) VALUES ("Zoo", "Spend the day enjoying the zoo");
INSERT INTO activities (name, description) VALUES ("Horseback riding", "Horseback riding on forest trails");
INSERT INTO activities (name, description) VALUES ("Frisbee golf", "Frisbee golf at the park");
INSERT INTO activities (name, description) VALUES ("Drawing", "Drawing and painting lessons");

INSERT INTO campsites (name, campsite_address_id, office_address_id, phone) VALUES ("SantaClara", 1, 1, "1234567890");
INSERT INTO addresses (address_1, city, state, zip) VALUES ('500 El Camino Real', 'Santa Clara', 'California', 95053);
INSERT INTO addresses (address_1, city, state,  zip) VALUES ('1234 First Street', 'Santa Clara', 'California', 95050);
INSERT INTO addresses (address_1, city, state,  zip) VALUES ('710 Vari Court', 'San Jose', 'California', 95051);
INSERT INTO addresses (address_1, city, state,  zip) VALUES ('222 Saratoga Ave', 'Mountain View', 'California', 94035);
INSERT INTO addresses (address_1, city, state,  zip) VALUES ('12 Mckenzie Street', 'Palo Alto', 'California', 94301);
INSERT INTO addresses (address_1, city, state,  zip) VALUES ('99 Tempview Drive', 'Sunnyvale', 'California', 94085);
INSERT INTO addresses (address_1, city, state,  zip) VALUES ('323 Creekview Street', 'San Jose', 'California', 95051);
INSERT INTO addresses (address_1, city, state,  zip) VALUES ('1500 Mcalistar Court', 'Sunnyvale', 'California', 94085);
INSERT INTO addresses (address_1, city, state,  zip) VALUES ('5433 Lambert Way', 'Sunnyvale', 'California', 94085);
INSERT INTO addresses (address_1, city, state,  zip) VALUES ('653 Imperial Ave', 'Palo Alto', 'California', 94301);
INSERT INTO addresses (address_1, city, state,  zip) VALUES ('4324 Market Street', 'Los Gatos', 'California', 95030);

INSERT INTO campsites (name, campsite_address_id, office_address_id, phone) VALUES ("NewYork", 2, 2, "2345678901");
INSERT INTO addresses (address_1, city, state,  zip) VALUES ('4683 Virginia Ave', 'New York', 'New York', 10001);
INSERT INTO addresses (address_1, city, state,  zip) VALUES ('1092 Sunset Road', 'Brooklyn', 'New York', 11223);
INSERT INTO addresses (address_1, city, state,  zip) VALUES ('201 Stagecoach Road', 'New Brunswick', 'New Jersey', 08899);
INSERT INTO addresses (address_1, city, state,  zip) VALUES ('120 Hendricks Court', 'Newark', 'New Jersey', 07100);
INSERT INTO addresses (address_1, city, state,  zip) VALUES ('605 Meadowside Street', 'Norwalk', 'Connecticut', 06850);
INSERT INTO addresses (address_1, city, state,  zip) VALUES ('409 Ford Drive', 'Darian', 'Connecticut', 06820);
INSERT INTO addresses (address_1, city, state,  zip) VALUES ('2356 Houston Street', 'Manhattan', 'New York', 10026);
INSERT INTO addresses (address_1, city, state,  zip) VALUES ('653 22nd Street', 'Manhattan', 'New York', 10026);
INSERT INTO addresses (address_1, city, state,  zip) VALUES ('32 Beverly Rd', 'Newark', 'New Jersey', 07100);
INSERT INTO addresses (address_1, city, state,  zip) VALUES ('6567 Madison Circle', 'Rutherford', 'New Jersey', 07073);

INSERT INTO campsites (name, campsite_address_id, office_address_id, phone) VALUES ("Portland", 3, 3, "2723457876");
INSERT INTO addresses (address_1, city, state,  zip) VALUES ('4356 Evergreen Rd', 'Lake Oswego', 'Oregon', 97034);
INSERT INTO addresses (address_1, city, state,  zip) VALUES ('10 Covington Road', 'Vancouver', 'Washington', 98660);
INSERT INTO addresses (address_1, city, state,  zip) VALUES ('1023 Riverside Dr', 'Portland', 'Oregon', 97024);
INSERT INTO addresses (address_1, city, state,  zip) VALUES ('12 Morrison Street', 'Portland', 'Oregon', 97021);
INSERT INTO addresses (address_1, city, state,  zip) VALUES ('545 Hawthorne Blvd', 'Milwaukie', 'Oregon', 97222);
INSERT INTO addresses (address_1, city, state,  zip) VALUES ('653 Gable Ave', 'Vancouver', 'Washington', 98660);

INSERT INTO campsites (name, campsite_address_id, office_address_id, phone) VALUES ("Atlanta", 4, 4, "8123450678");
INSERT INTO addresses (address_1, city, state,  zip) VALUES ('210 Glenn St', 'Atlanta', 'Georgia', 30301);
INSERT INTO addresses (address_1, city, state,  zip) VALUES ('1045 Scott Circle', 'Forest Park', 'Georgia', 30297);
INSERT INTO addresses (address_1, city, state,  zip) VALUES ('435 Virgina Ave', 'Atlanta', 'Georgia', 30301);
INSERT INTO addresses (address_1, city, state,  zip) VALUES ('1020 Bromack Dr', 'East Point', 'Georgia', 30344);
INSERT INTO addresses (address_1, city, state,  zip) VALUES ('4565 Conley Road', 'Forest Park', 'Georgia', 30297);
INSERT INTO addresses (address_1, city, state,  zip) VALUES ('6556 Church St', 'Scottdale', 'Georgia', 30079);
INSERT INTO addresses (address_1, city, state,  zip) VALUES ('43 Norman Road', 'Scottdale', 'Georgia', 30079);

INSERT INTO campsites (name, campsite_address_id, office_address_id, phone) VALUES ("Chicago", 5, 5, "3267865467");
INSERT INTO addresses (address_1, city, state,  zip) VALUES ('5798 Western Ave', 'Chicago', 'Illinois', 60290);
INSERT INTO addresses (address_1, city, state,  zip) VALUES ('432 Adams St', 'Chicago', 'Illinois', 60604);
INSERT INTO addresses (address_1, city, state,  zip) VALUES ('1033 Ashland Ave', 'Chicago', 'Illinois', 60612);
INSERT INTO addresses (address_1, city, state,  zip) VALUES ('432 Murberry Road', 'Cicero', 'Illinois', 60804);
INSERT INTO addresses (address_1, city, state,  zip) VALUES ('20 Harvey Park', 'Oak Lawn', 'Illinois', 60453);
INSERT INTO addresses (address_1, city, state,  zip) VALUES ('354 Story Island Ave', 'Elmwood Park', 'Illinois', 60707);
INSERT INTO addresses (address_1, city, state,  zip) VALUES ('5466 Jentry Way', 'Elmwood Park', 'Illinois', 60707);

INSERT INTO camp_sessions (campsite_id, start_date, end_date, base_price) VALUES (1, "2016-06-06", "2016-06-17", 800.00);
INSERT INTO camp_sessions (campsite_id, start_date, end_date, base_price) VALUES (1, "2016-06-20", "2016-07-01", 650.00);
INSERT INTO camp_sessions (campsite_id, start_date, end_date, base_price) VALUES (1, "2016-07-04", "2016-07-15", 450.00);
INSERT INTO camp_sessions (campsite_id, start_date, end_date, base_price) VALUES (1, "2016-07-18", "2016-07-29", 720.00);
INSERT INTO camp_sessions (campsite_id, start_date, end_date, base_price) VALUES (1, "2016-08-01", "2016-08-12", 650.00);
INSERT INTO camp_sessions (campsite_id, start_date, end_date, base_price) VALUES (1, "2016-08-15", "2016-08-26", 580.00);
INSERT INTO camp_sessions (campsite_id, start_date, end_date, base_price) VALUES (1, "2016-08-08", "2016-08-12", 300.00);
INSERT INTO camp_sessions (campsite_id, start_date, end_date, base_price) VALUES (1, "2016-08-22", "2016-08-29", 300.00);
INSERT INTO camp_sessions (campsite_id, start_date, end_date, base_price) VALUES (2, "2016-06-06", "2016-06-10", 400.00);
INSERT INTO camp_sessions (campsite_id, start_date, end_date, base_price) VALUES (2, "2016-06-20", "2016-07-01", 750.00);
INSERT INTO camp_sessions (campsite_id, start_date, end_date, base_price) VALUES (2, "2016-07-04", "2016-07-08", 350.00);
INSERT INTO camp_sessions (campsite_id, start_date, end_date, base_price) VALUES (2, "2016-07-11", "2016-07-15", 450.00);
INSERT INTO camp_sessions (campsite_id, start_date, end_date, base_price) VALUES (2, "2016-07-18", "2016-07-29", 720.00);
INSERT INTO camp_sessions (campsite_id, start_date, end_date, base_price) VALUES (2, "2016-08-01", "2016-08-12", 650.00);
INSERT INTO camp_sessions (campsite_id, start_date, end_date, base_price) VALUES (2, "2016-08-15", "2016-08-19", 480.00);
INSERT INTO camp_sessions (campsite_id, start_date, end_date, base_price) VALUES (2, "2016-08-22", "2016-08-29", 300.00);
INSERT INTO camp_sessions (campsite_id, start_date, end_date, base_price) VALUES (3, "2016-06-06", "2016-06-17", 700.00);
INSERT INTO camp_sessions (campsite_id, start_date, end_date, base_price) VALUES (3, "2016-06-20", "2016-06-27", 450.00);
INSERT INTO camp_sessions (campsite_id, start_date, end_date, base_price) VALUES (3, "2016-07-04", "2016-07-15", 650.00);
INSERT INTO camp_sessions (campsite_id, start_date, end_date, base_price) VALUES (3, "2016-07-04", "2016-07-15", 450.00);
INSERT INTO camp_sessions (campsite_id, start_date, end_date, base_price) VALUES (3, "2016-07-18", "2016-07-29", 720.00);
INSERT INTO camp_sessions (campsite_id, start_date, end_date, base_price) VALUES (3, "2016-08-01", "2016-08-12", 650.00);
INSERT INTO camp_sessions (campsite_id, start_date, end_date, base_price) VALUES (3, "2016-08-15", "2016-08-19", 480.00);
INSERT INTO camp_sessions (campsite_id, start_date, end_date, base_price) VALUES (3, "2016-08-22", "2016-08-29", 300.00);
INSERT INTO camp_sessions (campsite_id, start_date, end_date, base_price) VALUES (4, "2016-06-06", "2016-06-10", 400.00);
INSERT INTO camp_sessions (campsite_id, start_date, end_date, base_price) VALUES (4, "2016-06-20", "2016-07-01", 750.00);
INSERT INTO camp_sessions (campsite_id, start_date, end_date, base_price) VALUES (4, "2016-07-04", "2016-08-10", 350.00);
INSERT INTO camp_sessions (campsite_id, start_date, end_date, base_price) VALUES (4, "2016-07-04", "2016-07-15", 450.00);
INSERT INTO camp_sessions (campsite_id, start_date, end_date, base_price) VALUES (4, "2016-07-18", "2016-07-29", 720.00);
INSERT INTO camp_sessions (campsite_id, start_date, end_date, base_price) VALUES (4, "2016-08-01", "2016-08-12", 650.00);
INSERT INTO camp_sessions (campsite_id, start_date, end_date, base_price) VALUES (4, "2016-08-15", "2016-08-19", 480.00);
INSERT INTO camp_sessions (campsite_id, start_date, end_date, base_price) VALUES (4, "2016-08-22", "2016-08-29", 300.00);
INSERT INTO camp_sessions (campsite_id, start_date, end_date, base_price) VALUES (5, "2016-06-06", "2016-06-10", 400.00);
INSERT INTO camp_sessions (campsite_id, start_date, end_date, base_price) VALUES (5, "2016-06-20", "2016-07-01", 750.00);
INSERT INTO camp_sessions (campsite_id, start_date, end_date, base_price) VALUES (5, "2016-07-04", "2016-08-10", 350.00);
INSERT INTO camp_sessions (campsite_id, start_date, end_date, base_price) VALUES (5, "2016-07-04", "2016-07-15", 560.00);
INSERT INTO camp_sessions (campsite_id, start_date, end_date, base_price) VALUES (5, "2016-07-18", "2016-07-29", 720.00);
INSERT INTO camp_sessions (campsite_id, start_date, end_date, base_price) VALUES (5, "2016-08-01", "2016-08-12", 700.00);
INSERT INTO camp_sessions (campsite_id, start_date, end_date, base_price) VALUES (5, "2016-08-15", "2016-08-26", 680.00);
INSERT INTO camp_sessions (campsite_id, start_date, end_date, base_price) VALUES (5, "2016-08-22", "2016-09-02", 800.00);

# These were generated using fakenamegenerator.com
INSERT INTO users (first_name, last_name, email, phone) VALUES ("Richard", "McDonald", "RichardSMcDonald@inbound.plus", 5087431076);
INSERT INTO users (first_name, last_name, email, phone) VALUES ("Delbert", "Ratliff", "DelbertCRatliff@inbound.plu", 9078481843);
INSERT INTO users (first_name, last_name, email, phone) VALUES ("Damien", "Greene", "DamienJGreene@inbound.plus", 9738993281);
INSERT INTO users (first_name, last_name, email, phone) VALUES ("Bryant", "Acosta", "BryantMAcosta@inbound.plus", 4692616278);
INSERT INTO users (first_name, last_name, email, phone) VALUES ("Katherine", "Rodrigue", "KatherineCRodrigue@inbound.plus", 5182139482);
INSERT INTO users (first_name, last_name, email, phone) VALUES ("Chad", "Carson", "ChadJCarson@inbound.plus", 7635252355);
INSERT INTO users (first_name, last_name, email, phone) VALUES ("Miranda", "Simpson", "mirandasimpson@gmail.com", 8340334567);
INSERT INTO users (first_name, last_name, email, phone) VALUES ("Mark", "Bills", "markckbills@hotmail.com", 6540982345);
INSERT INTO users (first_name, last_name, email, phone) VALUES ("Nicole", "Rogers", "nicrogers@gmail.com", 9430983332);
INSERT INTO users (first_name, last_name, email, phone) VALUES ("Sarah", "Smith", "sarahJsmith@cisco.com", 5468764345);
INSERT INTO users (first_name, last_name, email, phone) VALUES ("Ryan", "Griffith", "rgriffith@aol.com", 4560983322);
INSERT INTO users (first_name, last_name, email, phone) VALUES ("Jessica", "Upridge", "jessupridge@hotmail.com", 9543333092);
INSERT INTO users (first_name, last_name, email, phone) VALUES ("Melissa", "Michaelson", "mmichaelson@live.com", 8495674333);
INSERT INTO users (first_name, last_name, email, phone) VALUES ("Martin", "Delgado", "martindelgado@gmail.com", 9426784543);
INSERT INTO users (first_name, last_name, email, phone) VALUES ("Amber", "Morris", "amorris@hotmail.com", 3409586790);
INSERT INTO users (first_name, last_name, email, phone) VALUES ("Samantha", "Stevens", "samstevens@gmail.com", 5406764342);

INSERT INTO questions (question, answer) VALUES ("How many camp locations are there?", "There are 5 camp locations.");
INSERT INTO questions (question, answer) VALUES ("How many sessions are there?", "Each campsite location has 8 camp sessions.");
INSERT INTO questions (question, answer) VALUES ("What is the deadline for signing up for a session?", "You can sign up as long as there is space available.");
INSERT INTO questions (question, answer) VALUES ("Are there vegetarian options for lunch?", "Yes your child may request a vegetarian option for lunch.");
INSERT INTO questions (question, answer) VALUES ("What happens if the session I want is already full?", "You may join our waitlist for this session free of charge. Just call 800-222-3443.");
INSERT INTO questions (question, answer) VALUES ("Will I receive a refund if I cancel my child's enrollment?", "You will receive a full refund up to 2 weeks before the camp. After this, you will only receive a refund of $120.");
INSERT INTO questions (question, answer) VALUES ("If my child is injured when will I be notified?", "The medical team will notify parents as soon as possible depending on the severity of the illness/injury.");
INSERT INTO questions (question, answer) VALUES ("Do you have a doctor or nurse onsite?", "Yes we have a medical team on site at all times.");
INSERT INTO questions (question, answer) VALUES ("Do you accomodate children with special needs?", "If your child has special medical need, please contact EdCamps prior to registration.");
INSERT INTO questions (question, answer) VALUES ("Should children bring spending money?", "Yes, snacks and drinks are available for purchase at the canteen throughout the day.");
INSERT INTO questions (question, answer) VALUES ("What if my child has allergies or medical conditions?", "Please make sure to inform us when you check in.");
INSERT INTO questions (question, answer) VALUES ("What should my child wear to camp?", "We recommend that students wear comfortable clothes like shorts, t-shirts and sneakers");
INSERT INTO questions (question, answer) VALUES ("Where do I pick up and drop off my child?", "Pick up & drop off will occur at the camp's main enterance. We will not release any children without parent supervision.");

INSERT INTO inventory (name, price, remaining) VALUES ("Sweatshirt", 25.00, 50);
INSERT INTO inventory (name, price, remaining) VALUES ("Water Bottle", 10.00, 30);
INSERT INTO inventory (name, price, remaining) VALUES ("Sticker", 3.00, 0);
INSERT INTO inventory (name, price, remaining) VALUES ("T-Shirt", 15.00, 20);
INSERT INTO inventory (name, price, remaining) VALUES ("Baseball cap", 10.00, 20);
INSERT INTO inventory (name, price, remaining) VALUES ("Backpack", 30.00, 30);
INSERT INTO inventory (name, price, remaining) VALUES ("Notebook", 3.00, 10);
